controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

place_details:
    path: /place/{id}
    controller: App\Controller\FrontController::details

app_home_register2:
    path: /inscription
    controller: App\Controller\RegisterController::index
    methods: ['GET', 'POST']